workflow_owner: cloudposse
workflow_repo: infra-live
workflow_filename: atmos-terraform-dispatch.yaml

runs-on-json: '["self-hosted"]'


aws-region: us-east-2
function-name: hello-world-cicd # this is the name of the lambda function and stack
source-folder: hello-world-python
artifacts-bucket: acme-core-ue2-auto-github-action-artifacts
artifacts-prefix: stage/{0}/lambda # {0} replaced by environment
artifacts-role-arn: arn:aws:iam::01234567890:role/acme-core-gbl-artifacts-gha-iam-lambda-cicd
cicd-role-arns:
  prod: arn:aws:iam::01234567890:role/acme-plat-gbl-prod-gha-iam-lambda-cicd
  staging: arn:aws:iam::01234567890:role/acme-plat-gbl-staging-gha-iam-lambda-cicd
  sandbox: arn:aws:iam::01234567890:role/acme-plat-gbl-sandbox-gha-iam-lambda-cicd
  dev: arn:aws:iam::01234567890:role/acme-plat-gbl-dev-gha-iam-lambda-cicd
