name: "Feature Branch: Build & Deploy Lambda"

on:
  # PR changes trigger a publish and deploy to dev
  pull_request:
    types: [opened, reopened, synchronize]


jobs:
  config:
    runs-on:
      - "self-hosted-default"

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: config
        uses: blablacar/action-config-levels@dc8ddbca36875e29f870e53bcc1160b7000ff5b2
        id: config
        with:
          output_properties: true
          patterns: |
            - .github/config/app.yaml
            
    outputs:
      config: ${{ steps.config.outputs.result }}
      
  # Publish jobs
  publish:
    uses: ./.github/workflows/reusable-publish-lambda-zip.yaml
    needs: config
    with: 
      function-name: ${{ fromJson(needs.config.outputs.config).function-name }}
      source-folder: ${{ fromJson(needs.config.outputs.config).source-folder }}
      artifacts-bucket: ${{ fromJson(needs.config.outputs.config).artifacts-bucket }}
      artifacts-prefix: ${{ fromJson(needs.config.outputs.config).artifacts-prefix }}
      artifacts-role-arn: ${{ fromJson(needs.config.outputs.config).artifacts-role-arn }}
      cicd-role-arns: ${{ toJson(fromJson(needs.config.outputs.config).cicd-role-arns) }}
      object-key: ${{ github.sha }}.zip
      aws-region: ${{ fromJson(needs.config.outputs.config).aws-region }}
      environment: dev
      runs-on-json: ${{ fromJson(needs.config.outputs.config).runs-on-json }}

  # Deploy jobs
  deploy:
    uses: ./.github/workflows/reusable-deploy-lambda.yaml
    needs: [config, publish]
    with:
      stack-name: plat-use2-dev
      component-name: lambda/hello-world-cicd
      workflow_owner: ${{ fromJson(needs.config.outputs.config).workflow_owner }}
      workflow_repo: ${{ fromJson(needs.config.outputs.config).workflow_repo }}
      workflow_filename: ${{ fromJson(needs.config.outputs.config).workflow_filename }}
      runs-on-json: ${{ fromJson(needs.config.outputs.config).runs-on-json }}
    secrets:
      gitops-token: ${{ secrets.PUBLIC_AND_PRIVATE_REPO_ACCESS_TOKEN_REPO }}
