name: "Build & Deploy Lambda: hello-world-python"

on:
  # PR changes trigger a publish and deploy to dev
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
    - hello-world-python/**
    - .github/workflows/lambda-hello-world-python.yaml
  # Pushes to the mainline branch (main) trigger a publish and deploy to staging
  push:
    branches:
    - main
    paths:
    - hello-world-python/**
    - .github/workflows/lambda-hello-world-python.yaml

jobs:
  # Publish jobs
  publish-dev:
    uses: ./.github/workflows/reusable-publish-lambda-zip.yaml
    if: ${{ github.event_name == 'pull_request' }}
    with:
      function-name: hello-world-python
      source-folder: lambda
      artifacts-bucket-and-prefix: cplive-core-ue1-public-lambda-artifacts/stage/dev/lambda/
      aws-region: us-east-2
    secrets:
      cicd-role-arn: ${{ secrets.CICD_ROLE_ARN }}
  publish-staging:
    uses: ./.github/workflows/reusable-publish-lambda-zip.yaml
    if: ${{ github.event_name == 'push' }}
    with:
      function-name: hello-world-python
      source-folder: hello-world-python
      artifacts-bucket-and-prefix: cplive-core-ue1-public-lambda-artifacts/stage/staging/lambda/
      aws-region: us-east-2
    secrets:
      cicd-role-arn: ${{ secrets.CICD_ROLE_ARN }}

  # Deploy jobs
  deploy-dev:
    uses: ./.github/workflows/reusable-deploy-lambda.yaml
    if: ${{ github.event_name == 'pull_request' }}
    needs: publish-dev
    with:
      function-name: hello-world-python
      stack: cplive-plat-ue2-dev-hello
    secrets:
      spacelift-api-key-id: ${{ secrets.SPACELIFT_API_KEY_ID }}
      spacelift-api-key-secret: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
  deploy-staging:
    uses: ./.github/workflows/reusable-deploy-lambda.yaml
    if: ${{ github.event_name == 'push' }}
    needs: publish-staging
    with:
      function-name: hello-world-python
      stack: cplive-plat-ue2-staging-hello
    secrets:
      spacelift-api-key-id: ${{ secrets.SPACELIFT_API_KEY_ID }}
      spacelift-api-key-secret: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
