name: "Promote Lambda to Prod: hello-world-python"

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/reusable-promote-lambda-zip.yaml
    with:
      function-name: hello-world-python
      artifacts-bucket-and-prefix: cplive-core-ue1-public-lambda-artifacts/stage/prod/lambda/
      aws-region: us-east-1
    secrets:
      cicd-role-arn: ${{ secrets.CICD_ROLE_ARN }}
      staging-role-arn: ${{ secrets.STAGING_ROLE_ARN }}
      prod-role-arn: ${{ secrets.PROD_ROLE_ARN }}
  deploy:
    uses: ./.github/workflows/reusable-deploy-lambda.yaml
    needs: publish
    with:
      function-name: hello-world-python
      stack: plat-dev
    secrets:
      spacelift-api-key-id: ${{ secrets.SPACELIFT_API_KEY_ID }}
      spacelift-api-key-secret: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
