name: Deploy Lambda
on:
  workflow_call:
    inputs:
      workflow_owner:
        required: true
        type: string
      workflow_repo:
        required: true
        type: string
      workflow_filename:
        required: true
        type: string
      workflow_ref:
        required: false
        type: string
        default: main
      stack-name:
        required: true
        type: string
      component-name:
        required: true
        type: string
      runs-on-json:
        required: true
        type: string
    secrets:
      gitops-token:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ${{ fromJSON(inputs.runs-on-json) }}
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.gitops-token }}
          repo: ${{ inputs.workflow_repo }}
          owner: ${{ inputs.workflow_owner }}
          workflow: ${{ inputs.workflow_filename }}
          ref: ${{ inputs.workflow_ref }}
          workflow_inputs: '{ "stack": "${{ inputs.stack-name}}", "component": "${{ inputs.component-name }}", "apply": true }'
      
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ secrets.gitops-token }}
          repo: ${{ inputs.workflow_repo }}
          owner: ${{ inputs.workflow_owner }}
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 300 # Optional
          poll_interval_ms: 5000 # Optional
