name: Publish Lambda Function
on:
  workflow_call:
    inputs:
      function-name:
        required: true
        type: string
      source-folder:
        required: true
        type: string
      artifacts-bucket-and-prefix:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      cicd-role-arn:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: self-hosted
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.cicd-role-arn }}
        aws-region: ${{ inputs.aws-region }}
    - name: Checkout
      uses: actions/checkout@master
    - name: Package Lambda
      run: |
        cd ${{ inputs.source-folder }} && zip ${{ github.sha }}.zip *
    - name: Push Lambda
      run: |
        aws s3 cp ${{ inputs.source-folder }}/${{ github.sha }}.zip s3://${{ inputs.artifacts-bucket-and-prefix }}/${{ inputs.function-name }}/ --sse
    - name: Write tag to SSM
      run: |
        aws ssm put-parameter --name /lambda/${{ inputs.function-name}}/tag --type String --value ${{ github.sha }} --overwrite
