name: Promote Lambda Function
on:
  workflow_call:
    inputs:
      function-name:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      source-object-key:
        required: true
        type: string
      target-object-key:
        required: true
        type: string
      source-artifacts-bucket-and-prefix:
        required: true
        type: string
      target-artifacts-bucket-and-prefix:
        required: true
        type: string
      artifacts-role-arn:
        required: true
        type: string
      cicd-role-arns:
        required: true
        type: string
      runs-on-json:
        required: true
        type: string
      environment:
        required: true
        type: string
permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ${{ fromJSON(inputs.runs-on-json) }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS credentials for artifacts role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.artifacts-role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: Copy Lambda to local
        env:
          SOURCE_OBJECT_URI: s3://${{ inputs.source-artifacts-bucket-and-prefix }}/${{ inputs.function-name }}/${{ inputs.source-object-key }}
          TARGET_OBJECT_URI: s3://${{ inputs.target-artifacts-bucket-and-prefix }}/${{ inputs.function-name }}/${{ inputs.target-object-key }}
        run: |
          aws s3 cp --sse AES256 $SOURCE_OBJECT_URI $TARGET_OBJECT_URI
      
      - uses: cloudposse/github-action-jq@main
        id: cicd-role-arns
        with:
          compact: true
          input: ${{ inputs.cicd-role-arns }}
          raw-output: true
          script: |-
            ."${{ inputs.environment }}"

      - name: Configure AWS credentials for 'cicd' role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-chaining: false
          unset-current-credentials: true
          role-to-assume: ${{ steps.cicd-role-arns.outputs.output }}
          aws-region: ${{ inputs.aws-region }}

      - name: Write tag to SSM
        run: |
          aws ssm put-parameter --name /lambda/${{ inputs.function-name }}/tag --type String --value ${{ inputs.target-object-key }} --overwrite
